### PR TITLE
Port telepathy static bindings to TelepathyGLib

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl, kindly review.

**Comment by quozl** [comment]
Reviewed to b71f2cb.

**Comment by chimosky** [comment]
@quozl, any required changes?.

**Comment by quozl** [comment]
Sure, if you like;
* [ ] gratuitous vertical space in call arguments; vertical space is a premium in text editors and IDEs, and the least number of lines the better for visual comprehension; ask yourself why you added more lines than are needed,
* [ ] the `=\` (equals backslash) is more commonly `= \` (equals space backslash) in our code base; in a quick search of 169524 lines of activity source code on my system, there is one instance of `=\` and 220 of `= \`,
* [ ] please test collaboration; the code you are changing is fundamental to collaboration, and without a test you've no idea if the change will work.

**Comment by chimosky** [comment]
@quozl kindly review, and i couldn't test with collaboration - i haven't set up a remote desktop yet -...please test and let me know.

**Comment by quozl** [comment]
No, won't review this one until https://github.com/sugarlabs/collabwrapper/pull/8 is merged and https://github.com/sugarlabs/collabwrapper/issues/1 is closed.

**Comment by rhl-bthr** [comment]
Collabwrapper isn't yet ported to TelepathyGLib, closing

**Pull request closed without merging**
