### PR TITLE
Adding support for special char. and numbers

### PR DESCRIPTION
**Pull request by Aniket21mathur**
The activity did not had support for special characters and numbers.

Using KEY values from https://gitlab.gnome.org/GNOME/gtk/raw/master/gdk/gdkkeysyms.h adding support for numbers abd special characters.

Fixes https://github.com/sugarlabs/collabedit/issues/3

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@quozl please review.Thanks!

**Comment by quozl** [comment]
Thanks.  It only supports certain keys, rather than all UTF-8 text that may be entered.  See https://github.com/sugarlabs/collabwrapper/blob/master/texteditor.py for an implementation that does not fixate on Gdk level, instead sharing the UTF-8 text.

**Comment by quozl** [comment]
Any progress toward full support for UTF-8?

**Comment by Aniket21mathur** [comment]
@quozl Sorry I quite forgot about this pull request.Start working on this soon.Thanks!

**Comment by quozl** [comment]
No worries.  You may be interested in the pull requests link in the GitHub navigation bar; it links to your pull requests.  With suitable change to the selection criteria, you can also list other people's pull requests.

tmp

**Comment by Aniket21mathur** [comment]
I gone through the source code and found out that these functions
`
        if key in utils.LETTERS_KEYS or key in utils.OTHER_KEYS:
            self.emit("insert-char", key, self.buffer.get_cursor_position()`
and 
`    def __insert_char_cb(self, view, key, position):
        if key in utils.LETTERS_KEYS:
            self.collab.post(dict(action="insert",
                                  key=Gdk.keyval_name(key),
                                  position=position))`
have checks for presence of the pressed keys in utils.py. So why don't we simply remove those checks 
and delete the utils.py file . I made the changes please review and test.
Thanks!

**Comment by quozl** [comment]
Thanks, well done.  Reviewed.

**Pull request merged**
